### PR TITLE
Remove usages of `this.$`, and update dependencies

### LINKED ISSUE #16: Resolve deprection: Using this.$() in a component has been deprecated
I think we can resolve this by installing `@ember/jquery` and replacing this.$ with a jquery import.

> DEPRECATION: Using this.$() in a component has been deprecated, consider using this.element [deprecation id: ember-views.curly-components.jquery-element] See https://emberjs.com/deprecations/v3.x#toc_jquery-apis for more details.

### PR DESCRIPTION
**Pull request by jenweber**
Added:
- devDependency and peerDependency on `@ember/jquery`

Changed
- replaced `this.$` with implicit import from jquery: `import $ from 'jquery'` and `this.$()` becomes `$(this.element)`
- ember-try scenarios
- Ember dependencies versions - updated to 3.15 via ember-cli-update
- Liquid-fire dependency version
- Replaced one case of `service('-router')` with the RouterService
- Switched package.json and travis to use > Node 10

Removed
- dependency on ember-cli-release. It seems it is probably not used.

Since I updated Ember-try scenarios and Node support, I believe this would be a major release.

Closes #16

### CODE REVIEW

**Comment by ef4** [comment]
Thanks.

Instead of adding `@ember/jquery` as a direct dependency here, I would prefer to make it a peerDependency, and document that apps must add `@ember/jquery` to use this addon. The rationale being, you really only want to end up with one copy of jquery in your app, so we care about using the same copy the app is using.

Also, tests are failing. Probably we need to change `node_js` to `"10"` in `.travis.yml`

**Comment by jenweber** [comment]
Unfortunately I move `@ember/jquery` to be a peer dependency, it breaks the dummy app:

```
Error: Could not find module `jquery` imported from `liquid-fire/running-transition`
```

Any thoughts on how to make this dependency available to the dummy app but not in the consuming app? I'm going to try putting it in devDependencies and peerDependencies. My understanding was that devDependencies don't get handed over to the consuming app.

**Comment by ef4** [comment]
I should clarify the peerDep thing: this PR already puts `@ember/jquery` in `devDependencies`, which is correct and necessary for testing this addon. But devDependencies don't come along when an app installs this addon. One solution to that is to move from `devDependencies` to `dependencies`, but I don't want to do that because it would bring it's own separate copy of JQuery into apps. Instead we should keep it in `devDependencies` (for testing) and also put it into `peerDependencies` (to tell apps they need to provide it).

**Comment by jenweber** [comment]
I see, that makes sense! Thanks!

**Comment by jenweber** [comment]
@ef4 do you know what the intent is of this section in travis?

```
    - stage: "Additional Tests"
      name: "Floating Dependencies"
      install:
        - npm install --no-package-lock
      script:
        - npm test
```

It results in the following error:

```
$ npm install --no-package-lock

npm ERR! Linux 4.4.0-101-generic

npm ERR! argv "/home/travis/.nvm/versions/node/v10.19.0/bin/node" "/home/travis/build/cardstack/ember-toolbars/node_modules/.bin/npm" "install" "--no-package-lock"

npm ERR! node v10.19.0

npm ERR! npm  v3.5.4
npm ERR! code MODULE_NOT_FOUND
npm ERR! Cannot find module 'internal/util/types'
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/cardstack/ember-toolbars/npm-debug.log
The command "npm install --no-package-lock" failed and exited with 1 during .
```

CI is also using an ancient version of npm, which is odd. The version is coming from a nested dependency that I will update.

**Comment by ef4** [comment]
It sees what happens if you get all the latest dependencies on NPM and try to run tests. At some point it was part of the standard addon blueprint, I didn't make it up AFAIK. We should probably just make travis.yml aligned with the current blueprint.

**Comment by jenweber** [comment]
@ef4 the tests on this are finally green. It took some work to make Travis happy.

**Pull request merged**
